name: AFL++ File Reader Fuzzer
on:
  workflow_dispatch:
    inputs:
      csv:
        description: Fuzz CSV inputs
        type: boolean
        default: true
      json:
        description: Fuzz JSON inputs
        type: boolean
        default: true
      parquet:
        description: Fuzz Parquet inputs
        type: boolean
        default: true

jobs:
  fuzz-file-readers:
    uses: c-herrewijn/duckdb-aflplusplus/.github/workflows/FileReaderFuzzer.yml@parallel-ci-build
    with:
      csv: ${{ inputs.csv }}
      json: ${{ inputs.json }}
      parquet: ${{ inputs.parquet }}
      duckdb_ref: 67a0a733f12119424dddee68aed6ad271792ec42
      duckdb_aflplusplus_repo: c-herrewijn/duckdb-aflplusplus
      duckdb_aflplusplus_ref: parallel-ci-build
      fuzzTime: 10
