# 3 ways of installing afl++

name: Afl++ Fuzzer
on: workflow_dispatch

jobs:
  fuzz1:
    name: fuzz1
    runs-on: ubuntu-24.04
    container:
      image: aflplusplus/aflplusplus:stable
      env:
        TEST_VAR: test_var
    steps:
      - name: test_step
        run: "afl-fuzz --version"

  fuzz2:
    name: fuzz2
    runs-on: aflplusplus/aflplusplus:stable
    steps:
      - name: test_step
        run: "afl-fuzz --version"

  # install and build afl++
  # https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/INSTALL.md
  fuzz3:
    name: fuzz3
    runs-on: ubuntu-24.04

    steps:
      - name: install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev automake cmake git flex bison libglib2.0-dev libpixman-1-dev python3-setuptools cargo libgtk-3-dev
          sudo apt-get install -y lld-14 llvm-14 llvm-14-dev clang-14 || sudo apt-get install -y lld llvm llvm-dev clang
          sudo apt-get install -y gcc-$(gcc --version|head -n1|sed 's/\..*//'|sed 's/.* //')-plugin-dev libstdc++-$(gcc --version|head -n1|sed 's/\..*//'|sed 's/.* //')-dev
      - name: Checkout AFL++
        uses: actions/checkout@v4
        with:
          repository: 'aflplusplus/aflplusplus'
          path: 'aflplusplus'
          ref: 'main'
      - name: build AFL++
        shell: bash
        run: |
          cd aflplusplus
          sudo make source-only
          sudo make install
      - name: where are we
        shell: bash
        run: |
          # where are we?
          echo "ENV content:"
          env
          echo "pwd:"
          pwd
          echo "ls -la ."
          ls -la .
          echo "ls -la /"
          ls -la /
          afl-fuzz --version
