name: Afl++ Fuzzer
on: workflow_dispatch

jobs:
  install-aflplusplus:
    name: Install AFL++
    runs-on: ubuntu-24.04

    steps:
      - name: print sha
        run: echo $GITHUB_SHA

      # https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/INSTALL.md
      - name: Install AFL++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev automake cmake git flex bison libglib2.0-dev libpixman-1-dev python3-setuptools cargo libgtk-3-dev
          sudo apt-get install -y lld-14 llvm-14 llvm-14-dev clang-14 || sudo apt-get install -y lld llvm llvm-dev clang
          sudo apt-get install -y gcc-$(gcc --version|head -n1|sed 's/\..*//'|sed 's/.* //')-plugin-dev libstdc++-$(gcc --version|head -n1|sed 's/\..*//'|sed 's/.* //')-dev

      - name: cmake version
        run: |
          cmake --version
          which cmake

      - name: Install DuckDB dependencies
        run: |
          sudo apt-get install -y ninja-build

      - name: Checkout duckdb_aflplusplus
        uses: actions/checkout@v4
        with:
          path: duckdb_aflplusplus

      - name: Checkout aflplusplus
        id: checkout-aflplusplus
        uses: actions/checkout@v4
        with:
          repository: aflplusplus/aflplusplus
          path: aflplusplus

      - name: Checkout duckdb
        uses: actions/checkout@v4
        with:
          repository: c-herrewijn/duckdb
          ref: CI_test
          path: duckdb

      # https://github.com/AFLplusplus/AFLplusplus/blob/stable/GNUmakefile
      - name: Cache AFL++ binaries
        id: cache-aflplusplus
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/afl*
            /usr/local/lib/afl/*
            /usr/local/share/doc/afl/*
            /usr/local/share/afl/*
            /usr/local/share/man/man8/*
            /usr/local/include/afl/*
            /aflplusplus/afl-fuzz
            /aflplusplus/afl-clang-fast
            /aflplusplus/afl-clang-fast++
          key: ${{ runner.os }}-aflplusplus-${{ steps.checkout-aflplusplus.outputs.commit }}

      - name: build AFL++
        if: steps.cache-aflplusplus.outputs.cache-hit != 'true'
        run: |
          cd aflplusplus
          sudo make source-only
          sudo make install

      - name: AFL++ version
        run: |
          afl-fuzz --version
          which afl-fuzz
          which afl-clang-fast || true
          afl-clang-fast --version || true
          echo 'fallback:'
          ${{ github.workspace }}/aflplusplus/afl-clang-fast --version

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}

      - name: ccache version
        run: |
          ccache --version
          which ccache

      - name: Build DuckDB
        run: |
          cd duckdb_aflplusplus/src
          make \
          DUCKDB_DIR=${{ github.workspace }}/duckdb \
          DUCKDB_AFLPLUSPLUS_DIR=${{ github.workspace }}/duckdb_aflplusplus \
          CC=${{ github.workspace }}/aflplusplus/afl-clang-fast \
          CXX=${{ github.workspace }}/aflplusplus/afl-clang-fast++ \
          BUILD_JEMALLOC=1 \
          USE_CCACHE=1 \
          duckdb-lib

      - name: duckdb version
        run: |
          ${{ github.workspace }}/duckdb/build/release/duckdb --version
