name: Click Bench Runner Dev
on:
  workflow_dispatch:

jobs:
  start-runner:
    name: Start self-hosted ec2 runner
    runs-on: ubuntu-latest
    env:
      instance_id: i-07fcb3ee34619ef2d
    steps:
      - name: Start EC2 runner
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: eu-north-1
        run: aws ec2 start-instances --instance-id ${{ env.instance_id }}

      # check status: https://eu-north-1.console.aws.amazon.com/ec2/home?region=eu-north-1#Instances
      - name: Wait for instance running
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: eu-north-1
        run: aws ec2 wait instance-running --instance-ids ${{ env.instance_id }}

  run-action:
    name: Action
    needs: start-runner
    runs-on: self-hosted
    steps:
      - run: echo test123

  shutdown:
    name: Stop self-hosted ec2 runner
    env:
      instance_id: i-07fcb3ee34619ef2d
    if: always()
    runs-on: ubuntu-latest
    needs:
      - start-runner
      - run-action
    steps:
      - name: Stop EC2 runner
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: eu-north-1
        run: aws ec2 stop-instances --instance-id ${{ env.instance_id }}
