name: Cross Version DB test
on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  osx-step-1:
    # Builds binaries for osx
    name: OSX Release
    runs-on: macos-14
    strategy:
      matrix:
        version: ['main' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.version }}

      - name: Checkout duckdb
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: c-herrewijn/duckdb
          ref: CI_test
          path: duckdb

      - name: Install Ninja
        run: brew install ninja file

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}

      - name: Build
        shell: bash
        run: cd duckdb && GEN=ninja CORE_EXTENSIONS='json;parquet' make
