# based on example: https://github.com/actions/hello-world-docker-action
# using an action from https://github.com/actions/

name: Hello Workflow

on:
  workflow_dispatch:
    inputs:
      my_name:
        description: name
        required: true
        type: string
      fuzzer_name:
        description: Name of the fuzzer
        required: true
        type: string

jobs:
  say-hello:
    name: say hello
    runs-on: ubuntu-24.04
    steps:
      - name: Greet action
        id: greet-action
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: ${{ inputs.my_name }}
      - name: Print output var
        run: echo "logging! the time is ${{ steps.greet-action.outputs.time }}"
      - name: Add to annotations
        run: echo "::notice::note that the time is ${{ steps.greet-action.outputs.time }}"

  dummy-fuzz:
    name: dummy fuzz
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fuzz step
        id: fuzz-step
        uses: ./.github/actions/fuzz
        with:
          fuzzer_name: ${{ inputs.fuzzer_name }}
      - name: Print fuzz output var
        run: echo "The fuzz output is ${{ steps.fuzz-step.outputs.fuzz_result }}"
      - name: Add to annotations
        run: "echo \"::notice::fuzz result: ${{ steps.fuzz-step.outputs.fuzz_result }}\""
