# based on example: https://github.com/actions/hello-world-docker-action
# using an action from https://github.com/actions/

name: Hello Workflow

on:
  workflow_dispatch:
    inputs:
      my_name:
        description: name
        required: true
        type: string

jobs:
  Say-Hello:
    name: say hello
    runs-on: ubuntu-24.04

    steps:
      - name: Greet action
        id: greet-action
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: ${{ inputs.my_name }}

      - name: Print output var
        run: echo "logging! the time is ${{ steps.greet-action.outputs.time }}"

      - name: Add to annotations
        run: echo "note that the time is ::notice::${{ steps.greet-action.outputs.time }}"
