# test the 'depth' of a sparse checkout

name: Sparse Checkout
on: workflow_dispatch

jobs:
  checkout_pattern1:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get install tree
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dummy_dir1
      - run: tree .

  checkout_pattern2:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get install tree
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dummy_dir1/*
      - run: tree .

  checkout_pattern3:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get install tree
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dummy_dir1/**
      - run: tree .
