# test the 'depth' of a sparse checkout -> all subdirectories and files are included

name: Sparse Checkout
on: workflow_dispatch

jobs:
  test-with-sparse-checkout:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get install tree
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dummy_dir1
      - run: tree .
